title: Tennis Learning Notes
description: Tennis strategy, learning notes, and reflections
theme: minima
author: Xin Yang
markdown: kramdown
highlighter: rouge
baseurl: "/tennis"
permalink: /:year/:month/:day/:title/

